### ISSUE TITLE
The root of "identity" is DNA

### ISSUE THREAD

**Issue by ajp8164** [ChristopherA/self-sovereign-identity#1]
Hi Christopher - I read your article with great anticipation that perhaps you could present a real approach to what you're referring to as "sovereign identity".  The concept is excellent and one that should be explored.  However, the article draws, IMO, a stark divide between "user" and "identity" or "digital identity".  This all implies to me that a "user" (a real person in the flesh) may possess multiple "identities".  Allowing this breaks the whole concept of even having an indentity.  A properly constructed solution demands that a "user" have exactly one "identity"; no more and no less.  To work properly an identity must be bound to the "user" at birth.  Separating these two concepts renders anything else that follows completely useless.  Identity must be bound to the identity bestowed upon us by God - your DNA.  The problem as I see it is that DNA is a "public key only" identity system.  Since I can easily obtain your DNA and there is no private key, well, it's a difficult problem as you know. Even if we move to the horrible discussion of implanting a private key at birth the problem persists.  Presumably the private key can be obtained by the user via some type of scanning method - which is easily accomplished by others.  I think an honest discussion of identity states right up front that "user" and "identity" and separate items of concern and that are bound and owned by the "user" and that ultimately the presentation and use of an "identity" does nothing to identify the "user".

**Comment by venam** [comment]
You seem to dismiss twins.  
Do you think they are one and the same person/identity?  
I think not, identity goes beyond the DNA.

**Comment by mitfik** [comment]
In my definition of identity is not what we have but what we are doing. Your "I" is build up during your whole life by what you are doing, where you go, who you meet. Hard coding that to one single object (or DNA as you wish) will be very risky as it will be easy to compromise or loose it).

Let's called all your possible interaction an "event" your identity is the sum of all those events. It could be a meeting with someone, doing something, achieving goals.  A good reference is to old times where we named people by what they were doing like John Blacksmith, nobody saw his identity on the paper, but by that what he was doing everyone could recognize him.

I think that this is a very interesting way of thinking about it. The question is how to collect those events, store them and recover in case of lost.
